spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/SupplierStock
    password: lugun

  application:
    name: SupplierStock
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: "true"
  flyway:
    baseline-on-migrate: true # Allows Flyway to baseline an existing DB
    enabled: true # Enable Flyway
    locations: classpath:db/migration # Default folder for migration scripts

  kafka:
    consumer:
      group-id: supplier-stock
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9092

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
